name: Create release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    name: Create release
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Prepare keystore
      run: echo ${{ secrets.android_keystore_base64 }} | base64 -d >$GITHUB_WORKSPACE/keystore.jks

    - name: Build signed package with gradle
      run: ./gradlew --no-configuration-cache --no-daemon app:assembleRelease
      env:
        ANDROID_KEYSTORE: ${{ github.workspace }}/keystore.jks
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
        ANDROID_KEY_ALIAS: ${{ secrets.android_key_alias }}
        ANDROID_KEY_PASSWORD: ${{ secrets.android_key_password }}
      
    - name: Create GH release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
        files: app/build/outputs/apk/release/*.apk
        fail_on_unmatched_files: true
